### ISSUE TITLE
some source files have to be transmitted in text mode or converted to EBCDIC

### ISSUE THREAD

**Issue by philippe-richard** [WASdev/sample.zos.provision.wlp#1]
all files from /workflows/templates/ must be transferred in text mode to your z/OS host, or converted to EBCDIC. The read.me file says
"1. Download the workflow files to a z/OS system running IBM Cloud Provisioning and Management. (workflows/templates/wlp-provisioning.sh may need to be converted to EBCDIC)"
But this should be extended to all files from  /workflows/templates/

**Comment by awisniew90** [comment]
Hi @philippe-richard. Are you seeing an explicit problem when those additional files are not converted to EBCDIC?  They should work whether in EBCDIC or ASCII.

**Comment by philippe-richard** [comment]
no, the pb is when you transfer the files they are copied as binary by 
default, and in that format they are unsuable in z/OSMF

If you transfer them in ASCII mode, they they end up being EBCDIC under 
z/OS, which is fne.
This is also the reason why in the READ.me file they mention (with 
reason):
"1. Download the workflow files to a z/OS system running IBM Cloud 
Provisioning and Management. (workflows/templates/wlp-provisioning.sh may 
need to be converted to EBCDIC)"
This warning is needed if the transfer is done by default for all 
files/directories, which is binary.
all xml files have to be ASCII/UTF8, which is fine, but all .sh all 
propoerties MUST BE EBCDIC , because z/OS is an EBCDIC animal....

Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 67346632 (38 6632)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2 
IBM Client Center, Montpellier WEB Server: http://w3.pssc.mop.ibm.com

=================================================

**Comment by awisniew90** [comment]
Thanks for the feedback @philippe-richard.  The workflows will still correctly function and execute the jcl and rexx scripts whether in ASCII/UTF-8 or EBCDIC. There is no requirement for the encoding of these files. wlp-provisioning.sh has a requirement outlined in the Readme.md given the nature of how the script is called at workflow execution. JCL and REXX scripts are called using the workflow <fileTemplate> entity. The wlp-provisioning.sh file needs to be referenced indirectly using the <inlineTemplate> entity in order to specify parameters on the script. For this reason, it needs to be converted in order to function properly.

**Comment by philippe-richard** [comment]
Thanks for the feedback.
I was not aware of that.
i looked at various other .rexx and .jcl files in my zOSMF, and they all 
appeared to be EBCDIC, so i figured out they had to be in that format.
but then i looked at the samples shipped with IBM z/OS Provisioning 
Toolkit V1.0 (zospt), and they all look similar as you describe.

Sorry for alerting about that; should i remove the 'issue' in github repo 
?


Cordialement, Philippe
  ====================

Philippe richard1/France/IBM@IBMFR (n'oubliez pas le 1...)
IBM Client Center, Montpellier

mailto:philippe_richard@fr.ibm.com   Mail: Cie IBM France Sce 146301
Phone: +33 4 67346632 (38 6632)    Rue de la Vieille Poste -CS 81021
Fax:       +33 4 67346477                      34060 Montpellier Cedex  2 
IBM Client Center, Montpellier WEB Server: http://w3.pssc.mop.ibm.com

=================================================

**Comment by awisniew90** [comment]
@philippe-richard No problem at all. I will go ahead and close out the issue. I'm fine with keeping the issue in the repo in case other users have a similar concern. I will also update the Readme.md to be more explicit about why wlp-provisioning.sh needs to be converted.  Thanks!
