### ISSUE TITLE
other EBCDIC files to transfer as ASCII or convert to EBCDIC

### ISSUE THREAD

**Issue by philippe-richard** [WASdev/sample.zos.provision.wlp#2]
/workflows/provisionWLP.mf
/properties/workflow_variables.properties

**Comment by awisniew90** [comment]
Hi @philippe-richard, these files should work in either EBCDIC or ASCII. Are you seeing an issue when they are not converted?

**Comment by awisniew90** [comment]
Closing this as it was resolved in a previous issue.
